dist: xenial
services:
  - docker

language: go

go:
  - "1.11.x"

# Only clone the most recent commit.
git:
  depth: 1

install: true

before_script:
  - go install -mod vendor github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -t -v ./...

script:
  - golangci-lint run
  - go test -v -race ./...

after_script:
  - docker build --tag "$DOCKER_REPO" .

deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: master