dist: xenial
services:
  - docker

language: go

go:
  - "1.11.x"

# Only clone the most recent commit.
git:
  depth: 1

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.12.5

before_script:
  - go get -t -v ./...

script:
  - golangci-lint run
  - go test -v -race ./...

before_deploy:
  - docker build --tag "$DOCKER_REPO" .

deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: master