language: go

services:
  - docker

go:
  - "1.10.x"

before_script:
  - go get -t -v ./...

script:
  - go test -v ./...
  - docker build --tag "$DOCKER_REPO" .

deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: master