version: "3"

services:
  arias:
    container_name: Arias
    build: .
    image: myanimestream/arias
    restart: always
    environment:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    ports:
      - 8080:80
      - 6800:6800
    volumes:
      - downloads:/downloads

volumes:
  downloads: {}