version: "3"

services:
  arias:
    container_name: Arias
    build: .
    image: myanimestream/arias
    restart: always
    networks:
      - internal

  aria2:
    container_name: Aria2
    image: xujinkai/aria2-with-webui
    restart: always
    ports:
      - 6880:80
      - 6800:6800
    networks:
      - internal

networks:
  internal: {}