package aria2

type Options struct {
	AllProxy                      string `json:"all-proxy,omitempty"`
	AllProxyPassword              string `json:"all-proxy-passwd,omitempty"`
	AllProxyUser                  string `json:"all-proxy-user,omitempty"`
	AllowOverwrite                string `json:"allow-overwrite,omitempty"`
	AllowPieceLengthChange        string `json:"allow-piece-length-change,omitempty"`
	AlwaysResume                  string `json:"always-resume,omitempty"`
	AsyncDNS                      string `json:"async-dns,omitempty"`
	AutoFileRenaming              string `json:"auto-file-renaming,omitempty"`
	BtEnableHookAfterHashCheck    string `json:"bt-enable-hook-after-hash-check,omitempty"`
	BtEnableLpd                   string `json:"bt-enable-lpd,omitempty"`
	BtExcludeTracker              string `json:"bt-exclude-tracker,omitempty"`
	BtExternalIP                  string `json:"bt-external-ip,omitempty"`
	BtForceEncryption             string `json:"bt-force-encryption,omitempty"`
	BtHashCheckSeed               string `json:"bt-hash-check-seed,omitempty"`
	BtLoadSavedMetadata           string `json:"bt-load-saved-metadata,omitempty"`
	BtMaxPeers                    string `json:"bt-max-peers,omitempty"`
	BtMetadataOnly                string `json:"bt-metadata-only,omitempty"`
	BtMinCryptoLevel              string `json:"bt-min-crypto-level,omitempty"`
	BtPrioritizePiece             string `json:"bt-prioritize-piece,omitempty"`
	BtRemoveUnselectedFile        string `json:"bt-remove-unselected-file,omitempty"`
	BtRequestPeerSpeedLimit       string `json:"bt-request-peer-speed-limit,omitempty"`
	BtRequireCrypto               string `json:"bt-require-crypto,omitempty"`
	BtSaveMetadata                string `json:"bt-save-metadata,omitempty"`
	BtSeedUnverified              string `json:"bt-seed-unverified,omitempty"`
	BtStopTimeout                 string `json:"bt-stop-timeout,omitempty"`
	BtTracker                     string `json:"bt-tracker,omitempty"`
	BtTrackerConnectTimeout       string `json:"bt-tracker-connect-timeout,omitempty"`
	BtTrackerInterval             string `json:"bt-tracker-interval,omitempty"`
	BtTrackerTimeout              string `json:"bt-tracker-timeout,omitempty"`
	CheckIntegrity                string `json:"check-integrity,omitempty"`
	Checksum                      string `json:"checksum,omitempty"`
	ConditionalGet                string `json:"conditional-get,omitempty"`
	ConnectTimeout                string `json:"connect-timeout,omitempty"`
	ContentDispositionDefaultUtf8 string `json:"content-disposition-default-utf8,omitempty"`
	Continue                      string `json:"continue,omitempty"`
	Dir                           string `json:"dir,omitempty"`
	DryRun                        string `json:"dry-run,omitempty"`
	EnableHttpKeepAlive           string `json:"enable-http-keep-alive,omitempty"`
	EnableHttpPipelining          string `json:"enable-http-pipelining,omitempty"`
	EnableMmap                    string `json:"enable-mmap,omitempty"`
	EnablePeerExchange            string `json:"enable-peer-exchange,omitempty"`
	FileAllocation                string `json:"file-allocation,omitempty"`
	FollowMetalink                string `json:"follow-metalink,omitempty"`
	FollowTorrent                 string `json:"follow-torrent,omitempty"`
	ForceSave                     string `json:"force-save,omitempty"`
	FtpPasswd                     string `json:"ftp-passwd,omitempty"`
	FtpPasv                       string `json:"ftp-pasv,omitempty"`
	FtpProxy                      string `json:"ftp-proxy,omitempty"`
	FtpProxyPasswd                string `json:"ftp-proxy-passwd,omitempty"`
	FtpProxyUser                  string `json:"ftp-proxy-user,omitempty"`
	FtpReuseConnection            string `json:"ftp-reuse-connection,omitempty"`
	FtpType                       string `json:"ftp-type,omitempty"`
	FtpUser                       string `json:"ftp-user,omitempty"`
	Gid                           string `json:"gid,omitempty"`
	HashCheckOnly                 string `json:"hash-check-only,omitempty"`
	Header                        string `json:"header,omitempty"`
	HttpAcceptGzip                string `json:"http-accept-gzip,omitempty"`
	HttpAuthChallenge             string `json:"http-auth-challenge,omitempty"`
	HttpNoCache                   string `json:"http-no-cache,omitempty"`
	HttpPasswd                    string `json:"http-passwd,omitempty"`
	HttpProxy                     string `json:"http-proxy,omitempty"`
	HttpProxyPasswd               string `json:"http-proxy-passwd,omitempty"`
	HttpProxyUser                 string `json:"http-proxy-user,omitempty"`
	HttpUser                      string `json:"http-user,omitempty"`
	HttpsProxy                    string `json:"https-proxy,omitempty"`
	HttpsProxyPasswd              string `json:"https-proxy-passwd,omitempty"`
	HttpsProxyUser                string `json:"https-proxy-user,omitempty"`
	IndexOut                      string `json:"index-out,omitempty"`
	LowestSpeedLimit              string `json:"lowest-speed-limit,omitempty"`
	MaxConnectionPerServer        string `json:"max-connection-per-server,omitempty"`
	MaxDownloadLimit              string `json:"max-download-limit,omitempty"`
	MaxFileNotFound               string `json:"max-file-not-found,omitempty"`
	MaxMmapLimit                  string `json:"max-mmap-limit,omitempty"`
	MaxResumeFailureTries         string `json:"max-resume-failure-tries,omitempty"`
	MaxTries                      string `json:"max-tries,omitempty"`
	MaxUploadLimit                string `json:"max-upload-limit,omitempty"`
	MetalinkBaseUri               string `json:"metalink-base-uri,omitempty"`
	MetalinkEnableUniqueProtocol  string `json:"metalink-enable-unique-protocol,omitempty"`
	MetalinkLanguage              string `json:"metalink-language,omitempty"`
	MetalinkLocation              string `json:"metalink-location,omitempty"`
	MetalinkOs                    string `json:"metalink-os,omitempty"`
	MetalinkPreferredProtocol     string `json:"metalink-preferred-protocol,omitempty"`
	MetalinkVersion               string `json:"metalink-version,omitempty"`
	MinSplitSize                  string `json:"min-split-size,omitempty"`
	NoFileAllocationLimit         bool   `json:"no-file-allocation-limit,omitempty,string"`
	NoNetrc                       bool   `json:"no-netrc,omitempty,string"`
	NoProxy                       bool   `json:"no-proxy,omitempty,string"`
	Out                           string `json:"out,omitempty"`
	ParameterizedUri              string `json:"parameterized-uri,omitempty"`
	Pause                         string `json:"pause,omitempty"`
	PauseMetadata                 string `json:"pause-metadata,omitempty"`
	PieceLength                   string `json:"piece-length,omitempty"`
	ProxyMethod                   string `json:"proxy-method,omitempty"`
	RealtimeChunkChecksum         string `json:"realtime-chunk-checksum,omitempty"`
	Referer                       string `json:"referer,omitempty"`
	RemoteTime                    string `json:"remote-time,omitempty"`
	RemoveControlFile             string `json:"remove-control-file,omitempty"`
	RetryWait                     string `json:"retry-wait,omitempty"`
	ReuseUri                      string `json:"reuse-uri,omitempty"`
	RpcSaveUploadMetadata         string `json:"rpc-save-upload-metadata,omitempty"`
	SeedRatio                     string `json:"seed-ratio,omitempty"`
	SeedTime                      string `json:"seed-time,omitempty"`
	SelectFile                    string `json:"select-file,omitempty"`
	Split                         string `json:"split,omitempty"`
	SshHostKeyMd                  string `json:"ssh-host-key-md,omitempty"`
	StreamPieceSelector           string `json:"stream-piece-selector,omitempty"`
	Timeout                       string `json:"timeout,omitempty"`
	UriSelector                   string `json:"uri-selector,omitempty"`
	UseHead                       string `json:"use-head,omitempty"`
	UserAgent                     string `json:"user-agent,omitempty"`
}
